function [RSSMatrix, gridLabel, x_real, y_real] = fp_collection(fingerprint, n, m)
%Simulation of data collection

%fingerprint -- the radio map generated by ray tracing
%n -- the number of APs
%m -- the number of collected fingerprint samples
%RSSMatrix -- m*n
%gridLabel -- the label of grids
%x_real -- real x-position of samples
%y_real -- real y-position of samples

%about the label£º
%a room of 20m * 15m, = 300 square grids, the label = 1:300, and the real positions are: x \in [1, 199]; y \in [1, 149];
%use 'label2xy' can get the center position of a grid (the real samples' position may not be at the center point)
%use 'xy2label' can get the label of a real sample

RSSMatrix = zeros(m, n);
gridLabel = zeros(m, 1);

[a, b, c] = size(fingerprint);
if(a ~= 199 && b ~= 149 && c < n)
    disp('fingerprint size is wrong.')
    return;
end

temp = randsample(199*149, m);
x_real = rem(temp - 1, 199) + 1;
y_real = ceil(temp/199);
x_real = x_real/10;
y_real = y_real/10;

for i = 1 : m
    RSSMatrix(i, 1:n) = fingerprint(x_real(i) * 10, y_real(i) * 10, 1:n);
    gridLabel(i) = xy2label(x_real(i), y_real(i));
end

end

